//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexHistory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
        public string cur1 { get; set; }
        public string cur2 { get; set; }
        public double amount { get; set; }
        public Nullable<double> result { get; set; }
    
        public virtual member member1 { get; set; }
    }
}
